CREATE TABLE INDITEX_GROUP(
    INDITEX_GROUP_ID INT AUTO_INCREMENT,
    BRAND_ID INT UNIQUE,
    BRAND VARCHAR(256),
    PRIMARY KEY (INDITEX_GROUP_ID)
);
CREATE TABLE PRICES (
    PRICES_ID INT AUTO_INCREMENT,
    BRAND_ID INT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID INT,
    PRIO INT,
    PRICE FLOAT,
    CURRENCY VARCHAR(3),
    PRIMARY KEY (PRICES_ID),
    FOREIGN KEY (BRAND_ID) REFERENCES INDITEX_GROUP(INDITEX_GROUP_ID)
);
CREATE SEQUENCE PRICES_SEQ MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE INDITEX_GROUP_SEQ MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 10;